name: Folder Info  
  
on:  
  push:  
   branches:  
    - main  
  
jobs:  
  folder-info:  
   runs-on: ubuntu-latest  
   steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  
    - name: Get folder info  
      run: |  
       folders=$(git ls-tree -d --name-only HEAD Migration)  
       for folder in $folders; do  
        if [[ $folder =~ ^[0-9]{14}$ ]]; then  
          commit_time=$(git log -1 --format=%ad --date=unix $folder)  
          echo "$folder,$commit_time"  
        fi  
       done > folder_info.csv  
    - name: Upload folder info  
      uses: actions/upload-artifact@v3  
      with:  
       name: folder_info.csv  
       path: folder_info.csv
