name: Folder Info

on:
  push:
    branches:
      - main

jobs:
  folder-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get folder info
        run: |
          #!/bin/bash

          # Set the folder path and filter criteria
          FOLDER_PATH="Migration"
          FILTER_CRITERIA="^[0-9]{14}$"

          # Get the repository's contents
          folders=$(git ls-tree -d --name-only HEAD "$FOLDER_PATH")

          # Initialize the output file
          echo "Folder Name,Commit Time" > folder_info.csv

          # Loop through each folder and extract information
          for folder in $folders; do
            if [[ ! $folder =~ ^[0-9]+$ ]]; then
              for subfolder in "$folder"/*; do
                if [[ -d $subfolder ]] && [[ "$(basename "$subfolder")" =~ $FILTER_CRITERIA ]]; then
                  commit_time=$(git log -1 --format=%ad --date=unix "$subfolder")
                  echo "$(basename "$folder"),$commit_time" >> folder_info.csv
                fi
              done
            fi
          done

      - name: Upload folder info
        uses: actions/upload-artifact@v3
        with:
          name: folder_info.csv
          path: folder_info.csv
