name: Folder Info

on:
  push:
    branches:
      - main

jobs:
  folder-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get folder info
        run: |
          folders=$(git ls-tree -d --name-only HEAD Migration)
          for folder in $folders; do
            if [[ ! $folder =~ ^[0-9]+$ ]]; then
              for subfolder in "$folder"/*; do
                if [[ -d $subfolder ]] && [[ "$(basename "$subfolder")" =~ ^[0-9]{14}$ ]]; then
                  commit_time=$(git log -1 --format=%ad --date=unix "$subfolder")
                  echo "$(basename "$folder"),$(basename "$subfolder"),$commit_time"
                fi
              done
            fi
          done > folder_info.csv

      - name: Upload folder info
        uses: actions/upload-artifact@v2
        with:
          name: folder_info.csv
          path: folder_info.csv
