name: Folder List

on:
  workflow_dispatch:

jobs:
  folder-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Gather folder information
        run: |
          folders=$(git ls-tree -r --name-only HEAD migration | grep -E '^[^0-9]+|^[0-9]{14}$')
          while IFS= read -r folder; do
            commit_time=$(git log -1 --format=%ct -- $folder)
            echo "$folder,$(date -d @$commit_time '+%Y-%m-%d %H:%M:%S')" 
          done <<< "$folders" > folder_list.csv

      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: folder_list.csv
          path: folder_list.csv
